[2024-02-27 14:50:20,434: INFO: main: Starting our pipeline]
[2024-03-18 16:50:31,219: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-18 16:50:31,219: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-18 16:50:31,219: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-18 16:50:31,219: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "src\MLOpsPipelines\utils\common.py", line 36, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 17, in main
    config = ConfigurationManager()
  File "src\MLOpsPipelines\config\configuration.py", line 19, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "src\MLOpsPipelines\utils\common.py", line 39, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-03-19 15:09:48,375: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:09:48,393: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:09:48,396: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:09:48,396: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 32, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-03-19 15:17:25,743: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:17:25,768: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:17:25,777: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:17:25,778: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 32, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 35, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-03-19 15:18:01,977: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:18:02,086: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:18:02,106: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:18:02,107: ERROR: main: First argument must be mapping or iterable]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 38, in read_yaml
    raise e
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 32, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable
[2024-03-19 15:23:23,492: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:23:23,492: ERROR: main: [Errno 2] No such file or directory: 'MLOps-pipelines-using-MLflow-and-DVC\\config\\config.yaml']
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 19, in __init__
    self.config = read_yaml(config_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 38, in read_yaml
    raise e
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'MLOps-pipelines-using-MLflow-and-DVC\\config\\config.yaml'
[2024-03-19 15:24:02,775: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:24:02,775: ERROR: main: [Errno 2] No such file or directory: 'MLOps-pipelines-using-MLflow-and-DVC\\config\\config.yaml']
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 19, in __init__
    self.config = read_yaml(config_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 38, in read_yaml
    raise e
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 29, in read_yaml
    with open(path_to_yaml) as yaml_file:
FileNotFoundError: [Errno 2] No such file or directory: 'MLOps-pipelines-using-MLflow-and-DVC\\config\\config.yaml'
[2024-03-19 15:24:32,270: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:24:32,270: ERROR: main: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x00000289CAB28310> does not match annotation type <class 'pathlib.Path'>]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 19, in __init__
    self.config = read_yaml(config_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 870, in __call__
    raise EnsureError(msg.format(arg=arg, f=self.f, t=templ, valt=type(value)))
ensure.main.EnsureError: Argument path_to_yaml of type <class 'str'> to <function read_yaml at 0x00000289CAB28310> does not match annotation type <class 'pathlib.Path'>
[2024-03-19 15:25:32,322: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:25:32,325: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:25:32,328: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:25:32,329: ERROR: main: First argument must be mapping or iterable]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 38, in read_yaml
    raise e
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 32, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable
[2024-03-19 15:30:35,609: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:30:35,609: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:30:35,609: ERROR: main: Return value of <function read_yaml at 0x000001A1C5862040> of type <class 'box.box.Box'> does not match annotation type <class 'box.config_box.ConfigBox'>]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 19, in __init__
    self.config = read_yaml(config_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 875, in __call__
    raise EnsureError(msg.format(f=self.f, t=self.return_templ, valt=type(return_val)))
ensure.main.EnsureError: Return value of <function read_yaml at 0x000001A1C5862040> of type <class 'box.box.Box'> does not match annotation type <class 'box.config_box.ConfigBox'>
[2024-03-19 15:30:54,844: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:30:54,844: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:30:54,844: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:30:54,844: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 36, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-03-19 15:32:40,801: INFO: trials: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:32:58,461: INFO: trials: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:35:43,761: INFO: trials: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:36:25,080: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:36:25,080: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:36:25,080: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:36:25,080: ERROR: main: yaml file is empty]
Traceback (most recent call last):
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 33, in read_yaml
    return ConfigBox(content)
  File "box\box.py", line 291, in box.box.Box.__init__
box.exceptions.BoxValueError: First argument must be mapping or iterable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 20, in __init__
    self.params = read_yaml(params_file_path)
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 872, in __call__
    return_val = self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 36, in read_yaml
    raise ValueError("yaml file is empty")
ValueError: yaml file is empty
[2024-03-19 15:42:45,168: INFO: trials: yaml file: params.yaml loaded successfully]
[2024-03-19 15:43:13,399: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:43:13,399: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:43:13,415: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:43:13,415: ERROR: main: expected str, bytes or os.PathLike object, not ConfigBox]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 22, in __init__
    create_directories([self.config, self.params])
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 55, in create_directories
    os.makedirs(path, exist_ok=True)
  File "C:\Users\BA\anaconda3\lib\os.py", line 208, in makedirs
    head, tail = path.split(name)
  File "C:\Users\BA\anaconda3\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not ConfigBox
[2024-03-19 15:45:36,891: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:45:36,891: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:45:36,900: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:45:36,900: ERROR: main: expected str, bytes or os.PathLike object, not ConfigBox]
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 19, in main
    config = ConfigurationManager()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 22, in __init__
    create_directories([self.config, self.params])
  File "C:\Users\BA\anaconda3\lib\site-packages\ensure\main.py", line 835, in __call__
    return self.f(*args, **kwargs)
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\utils\common.py", line 55, in create_directories
    os.makedirs(path, exist_ok=True)
  File "C:\Users\BA\anaconda3\lib\os.py", line 208, in makedirs
    head, tail = path.split(name)
  File "C:\Users\BA\anaconda3\lib\ntpath.py", line 185, in split
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not ConfigBox
[2024-03-19 15:47:17,203: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:47:17,203: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:47:17,203: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:47:17,215: INFO: common: created directory at: artifacts]
[2024-03-19 15:47:17,217: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 15:47:17,218: ERROR: main: __init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 29, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: __init__() got an unexpected keyword argument 'source_URL'
[2024-03-19 15:48:14,354: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:48:14,354: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:48:14,354: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:48:14,354: INFO: common: created directory at: artifacts]
[2024-03-19 15:48:14,354: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 15:48:14,368: ERROR: main: __init__() got an unexpected keyword argument 'source_URL']
Traceback (most recent call last):
  File "d:/BSL/AI/Projects/MLOps-pipelines-using-MLflow-and-DVC/main.py", line 13, in <module>
    obj.main()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\pipeline\stage_01_data_ingestion.py", line 20, in main
    data_ingestion_config = config.get_data_ingestion_config()
  File "d:\BSL\AI\Projects\MLOps-pipelines-using-MLflow-and-DVC\src\MLOpsPipelines\config\configuration.py", line 29, in get_data_ingestion_config
    data_ingestion_config = DataIngestionConfig(
TypeError: __init__() got an unexpected keyword argument 'source_URL'
[2024-03-19 15:51:26,496: INFO: main: >>>>>> stage Data Ingestion stage started <<<<<<]
[2024-03-19 15:51:26,496: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-19 15:51:26,516: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-19 15:51:26,519: INFO: common: created directory at: artifacts]
[2024-03-19 15:51:26,521: INFO: common: created directory at: artifacts/data_ingestion]
[2024-03-19 15:51:26,523: INFO: data_ingestion: Downloading data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 15:51:41,775: INFO: data_ingestion: Downloaded data from https://drive.google.com/file/d/1z0mreUtRmR-P-magILsDR3T7M6IkGXtY/view?usp=sharing into file artifacts/data_ingestion/data.zip]
[2024-03-19 15:51:43,943: INFO: main: >>>>>> stage Data Ingestion stage completed <<<<<<

x==========x]
[2024-03-27 05:33:50,786: INFO: main: *******************]
[2024-03-27 05:33:50,817: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-03-27 05:33:50,832: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-03-27 05:33:50,840: INFO: common: yaml file: params.yaml loaded successfully]
[2024-03-27 05:33:50,843: INFO: common: created directory at: artifacts]
[2024-03-27 05:33:50,844: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-03-27 05:33:51,989: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-03-27 05:33:53,407: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-06 05:50:18,801: INFO: main: *******************]
[2024-04-06 05:50:18,835: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-06 05:50:18,889: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 05:50:18,895: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 05:50:18,898: INFO: common: created directory at: artifacts]
[2024-04-06 05:50:18,899: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-06 05:50:20,032: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-06 05:50:22,940: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-06 05:50:22,942: INFO: main: *******************]
[2024-04-06 05:50:22,944: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-06 05:50:22,951: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 05:50:22,958: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 05:50:22,960: INFO: common: created directory at: artifacts]
[2024-04-06 05:50:22,962: INFO: common: created directory at: artifacts\training]
[2024-04-06 05:52:18,503: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-06 05:52:18,512: INFO: main: *******************]
[2024-04-06 05:52:18,513: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 05:52:18,527: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 05:52:18,536: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 05:52:18,541: INFO: common: created directory at: artifacts]
[2024-04-06 05:52:49,198: INFO: common: json file saved at: scores.json]
[2024-04-06 05:52:49,203: INFO: common: json file saved at: scores.json]
[2024-04-06 05:52:49,204: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-06 06:01:25,587: INFO: main: *******************]
[2024-04-06 06:01:25,588: INFO: main: >>>>>> stage Prepare base model started <<<<<<]
[2024-04-06 06:01:25,598: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:01:25,603: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:01:25,604: INFO: common: created directory at: artifacts]
[2024-04-06 06:01:25,606: INFO: common: created directory at: artifacts/prepare_base_model]
[2024-04-06 06:01:26,848: WARNING: saving_utils: Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.]
[2024-04-06 06:01:30,434: INFO: main: >>>>>> stage Prepare base model completed <<<<<<

x==========x]
[2024-04-06 06:01:30,436: INFO: main: *******************]
[2024-04-06 06:01:30,436: INFO: main: >>>>>> stage Training started <<<<<<]
[2024-04-06 06:01:30,446: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:01:30,453: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:01:30,455: INFO: common: created directory at: artifacts]
[2024-04-06 06:01:30,456: INFO: common: created directory at: artifacts\training]
[2024-04-06 06:03:13,937: INFO: main: >>>>>> stage Training completed <<<<<<

x==========x]
[2024-04-06 06:03:13,938: INFO: main: *******************]
[2024-04-06 06:03:13,939: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 06:03:13,945: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:03:13,952: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:03:13,953: INFO: common: created directory at: artifacts]
[2024-04-06 06:03:49,281: INFO: common: json file saved at: scores.json]
[2024-04-06 06:03:49,283: INFO: common: json file saved at: scores.json]
[2024-04-06 06:03:49,284: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-06 06:09:17,315: INFO: main: *******************]
[2024-04-06 06:09:17,315: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 06:09:17,331: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:09:17,336: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:09:17,337: INFO: common: created directory at: artifacts]
[2024-04-06 06:09:50,305: INFO: common: json file saved at: scores.json]
[2024-04-06 06:09:50,307: INFO: common: json file saved at: scores.json]
[2024-04-06 06:09:50,308: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-06 06:13:23,278: INFO: main: *******************]
[2024-04-06 06:13:23,278: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 06:13:23,283: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:13:23,288: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:13:23,289: INFO: common: created directory at: artifacts]
[2024-04-06 06:13:54,398: INFO: common: json file saved at: scores.json]
[2024-04-06 06:13:54,462: INFO: common: json file saved at: scores.json]
[2024-04-06 06:13:54,470: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-06 06:19:09,805: INFO: main: *******************]
[2024-04-06 06:19:09,816: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 06:19:09,821: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:19:09,827: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:19:09,829: INFO: common: created directory at: artifacts]
[2024-04-06 06:19:47,227: INFO: common: json file saved at: scores.json]
[2024-04-06 06:19:47,233: INFO: common: json file saved at: scores.json]
[2024-04-06 06:19:47,234: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
[2024-04-06 06:21:48,435: INFO: main: *******************]
[2024-04-06 06:21:48,436: INFO: main: >>>>>> stage Evaluation stage started <<<<<<]
[2024-04-06 06:21:48,551: INFO: common: yaml file: config\config.yaml loaded successfully]
[2024-04-06 06:21:48,564: INFO: common: yaml file: params.yaml loaded successfully]
[2024-04-06 06:21:48,566: INFO: common: created directory at: artifacts]
[2024-04-06 06:22:24,217: INFO: common: json file saved at: scores.json]
[2024-04-06 06:22:24,219: INFO: common: json file saved at: scores.json]
[2024-04-06 06:22:24,220: INFO: main: >>>>>> stage Evaluation stage completed <<<<<<

x==========x]
